name: Release

#on:
#  push:
#    branches:
#      - latest
#      - latest-next
#      - next
#      - beta
#      - alpha
#      - "*.x" # maintenance releases branches

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 7.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.x"
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
